
services:
  postgres:
    image: postgres:16
    container_name: toystore-customer-db
    restart: always
    environment:
      POSTGRES_DB: toystore-customer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  app:
    build: .
    container_name: toystore-customer-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/toystore-customer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
    networks:
      - backend
volumes:
  postgres_data:

networks:
  backend:
